class ImportantDates
  
  SUBMISSION_START_DATETIME = Time.zone.local(2012, 4, 11, 0, 0, 0)
  SUBMISSION_START_DATE = SUBMISSION_START_DATETIME.to_date
  SUBMISSION_END_DATETIME = Time.zone.local(2012, 5, 29, 23, 59, 59)
  SUBMISSION_END_DATE = SUBMISSION_END_DATETIME.to_date
  ACCEPTANCE_NOTIFICATION_DATETIME = Time.zone.local(2012, 7, 11, 23, 59, 59)
  ACCEPTANCE_NOTIFICATION_DATE = ACCEPTANCE_NOTIFICATION_DATETIME.to_date
  AUTHORS_INSCRIPTION_END_DATETIME = Time.zone.local(2012, 7, 24, 23, 59, 59)
  AUTHORS_INSCRIPTION_END_DATE = AUTHORS_INSCRIPTION_END_DATETIME.to_date
  PROGRAM_PUBLISH_DATETIME = Time.zone.local(2012, 8, 1, 23, 59, 59)
  
end