class ImportantDates
  
  SUBMISSION_START_DATETIME = Ability::SESSION_OPEN_SUBMISSION
  SUBMISSION_START_DATE = SUBMISSION_START_DATETIME.to_date
  SUBMISSION_END_DATETIME = Ability::SESSION_SUBMISSION_DEADLINE
  SUBMISSION_END_DATE = SUBMISSION_END_DATETIME.to_date
  ACCEPTANCE_NOTIFICATION_DATETIME = Ability::AUTHOR_NOTIFICATION_DEADLINE
  ACCEPTANCE_NOTIFICATION_DATE = ACCEPTANCE_NOTIFICATION_DATETIME.to_date
  AUTHORS_INSCRIPTION_END_DATETIME = Ability::AUTHOR_CONFIRMATION_DEADLINE
  AUTHORS_INSCRIPTION_END_DATE = AUTHORS_INSCRIPTION_END_DATETIME.to_date
  PROGRAM_PUBLISH_DATETIME = Ability::REGISTRATION_DEADLINE
  
end